### ISSUE TITLE
Eureka, inc.でのAll in one: GCP Vertex AIのMLOps/サービング: EKS GPU推論環境 のブログ記事をそれぞれ追加

### ISSUE THREAD

**Issue by fukubaka0825** [masatakashiwagi/mlops-practices#21]
# 概要
Eureka, inc. の以下の事例ブログをそれぞれ追加
- All in One 
  - [オンライン機械学習サービスとしてGCP Vertex AIのMLOpsを導入した話](https://medium.com/eureka-engineering/vertex-ai-mlops-b74cdff19681)
- サービング
  - [How to make GPU inference environment of image category classification production-ready with EKS/Kubernetes](https://medium.com/eureka-engineering/how-to-make-gpu-inference-environment-of-image-category-classification-production-ready-with-88922fb09401)

**Comment by fukubaka0825** [comment]
@masatakashiwagi 
こちらpull request起票させていただきました 🙏

**Comment by masatakashiwagi** [comment]
事例を追加したので，このIssueはCloseしますー！
