### ISSUE TITLE
MLOps導入でAmazon SageMaker PipelineによりMLワークフロー構築の話

### ISSUE THREAD

**Issue by icoxfog417** [masatakashiwagi/mlops-practices#25]
素晴らしいまとめを作っていただきありがとうございます。

StanbyさんでMLOpsのLevel1:MLパイプラインの自動化のうちモデル作成と実験記録管理を実現した事例があったので掲載してはと思いIssueを起票させていただきました。SageMaker Pipelineで前処理・学習・評価の処理をパイプライン化しています。

https://techblog.stanby.co.jp/entry/mlops

掲載するとしたらKnowledgeのPipelineでよいでしょうか? もし差し支えなければPull Requestを送らせていただきます。

https://masatakashiwagi.github.io/mlops-practices/knowledge/

Practicesは、MLOpsのLevel0, 1, 2と段階ごとに構成されているとサイトを訪問された方が自分の段階に応じて事例を参照できてよいのかも、と思いました！ Tipsの方にFeature Storeは、Pipelineは、などMLOps構成要素個別の深い話があると 、Knowledge で全体感をつかんで細かいところはTipsで補完、と整理できるかもしれません。

**Comment by masatakashiwagi** [comment]
@icoxfog417 
Issue作成して頂いてありがとうございます！
是非PR出して頂けると嬉しいです😆

>Practicesは、MLOpsのLevel0, 1, 2と段階ごとに構成されているとサイトを訪問された方が自分の段階に応じて事例を参照できてよいのかも、と思いました！ Tipsの方にFeature Storeは、Pipelineは、などMLOps構成要素個別の深い話があると 、Knowledge で全体感をつかんで細かいところはTipsで補完、と整理できるかもしれません。

→ この辺りアップデートしたいと思っていたので，アドバイス大変助かります！確かにMLOpsのLevel毎に分ける+それぞれの詳細なトピックはTipsの方へというのは良さそうだと思います！

質問なんですが，MLOpsのLevel毎に分けるというのはそれぞれのLevelに応じた事例があれば，それを載せるという感じでしょうか？それともLevelの説明をするという感じでしょうか？

**Comment by icoxfog417** [comment]
@masatakashiwagi さん、ご回答ありがとうございます！Pull Requestを送らせていただきます。

Levelに応じた事例を載せるイメージをしていました。Level定義がいくつか存在するので難しいところではありますが、 個人的には1: 学習の自動化、2: デプロイの自動化、3: 再学習の自動化(完全自動化)がオーソドックスな印象です。

**Comment by masatakashiwagi** [comment]
@icoxfog417 
提案ありがとうございます！上で挙げてくださったような形で「Knowledge」と「Tips」を再構成していこうと思います🙏
以下のIssueで対応して行く予定です！
https://github.com/masatakashiwagi/mlops-practices/issues/29

本Issueの内容はPRマージしましたので，Closeさせて頂きます！
