### ISSUE TITLE
Amazon SageMakerでつくるMLOps -効率的な機械学習の開発・運用環境-

### ISSUE THREAD

**Issue by icoxfog417** [masatakashiwagi/mlops-practices#30]
AWSでのMLOps構築について、わかりやすい資料とフィードバックがあったため追加させていただければ幸いです。

[Amazon SageMakerでつくるMLOps -効率的な機械学習の開発・運用環境-](https://pages.awscloud.com/rs/112-TZM-766/images/attch_464048_533026_mp4_video_001_T2-4_MLT_AWS-Innovate-AIML_2022_deck.pdf)
  * [資料参照した方からのフィードバック①](https://twitter.com/d5onoda/status/1536336675571646464?s=20&t=fctW43DTqinO6rEiRx7oHg)
  * [資料参照した方からのフィードバック②](https://twitter.com/morihaya55/status/1538900952262258688?s=20&t=fctW43DTqinO6rEiRx7oHg)

https://masatakashiwagi.github.io/mlops-practices/knowledge/

Guidesのプレゼンテーションに入ると思いましたが、Practicesのプレゼンテーションどちらか微妙だったため確認させてください(Guidesは理論的な内容でPracticesは実践的な内容という理解で、本資料はMLOpsの実践例ではないためGudesと解釈しています)。確定したらPull Requestを送らせていただければと思います。

**Comment by masatakashiwagi** [comment]
丁寧なIssue作成ありがとうございます！
そうですね，こちらは「Guides」のプレゼンテーションに追加する形でお願いします！

こちらの資料，AWSでMLOpsを始める時にとても参考になる資料ですよね😊
Issueに起票して頂いて助かります🙏

**Comment by masatakashiwagi** [comment]
@icoxfog417 
丁寧なIssue作成ありがとうございます！
そうですね，こちらは「Guides」のプレゼンテーションに追加する形でお願いします！

こちらの資料，AWSでMLOpsを始める時にとても参考になる資料ですよね😊
Issueに起票して頂いて助かります🙏

**Comment by icoxfog417** [comment]
御回答ありがとうございます！PRを作成しました。

**Comment by masatakashiwagi** [comment]
@icoxfog417 
ガイドの追加ありがとうございます！PRマージしたので，このIssueはCloseさせて貰います．
